include: package:lint/strict.yaml 
linter:
  rules:
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.config.dart"
    - "build/**"
    - "test/**"