name: mote
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10
  get_it: ^7.6.7
  injectable: ^2.4.4
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  talker_bloc_logger: ^4.4.1
  talker_flutter: ^4.4.1
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  lint: ^2.3.0
  flutter_gen: ^5.7.0

flutter_gen:
  output: lib/config/utils/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/bottom_bar/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
